# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting on merge and push
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter build web --web-renderer html --release --dart-define="SERVER_API_URL=https://europe-west1-area-37a17.cloudfunctions.net/api/"
        working-directory: ./clt
      - run: flutter build apk --release --dart-define="SERVER_API_URL=https://europe-west1-area-37a17.cloudfunctions.net/api/"
        working-directory: ./clt
      - run: mv build/app/outputs/flutter-apk/app-release.apk build/web/client.apk
        working-directory: ./clt
      - uses: actions/upload-artifact@master
        with:
          name: web
          path: clt/build/web
      - uses: actions/upload-artifact@master
        with:
          name: client.apk
          path: clt/build/web/client.apk
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AREA_37A17 }}'
          channelId: live
          projectId: area-37a17
